### ISSUE TITLE
@vue/composition-api is always installed

### ISSUE THREAD

**Issue by darthf1** [intlify/routing#19]
### Describe the bug

I'm on Vue 3, and require `vue-i18n-routing` `0.7.0` in my `package.json`.

When I run `pnpm i --no-optional`, I get the following  error message:

![image](https://user-images.githubusercontent.com/17253332/197040613-faa95d1c-f4ab-48fd-af6c-e26d7d890fd2.png)

### Reproduction

Cannot reproduce on stackblitz, please advice.

### System Info

```Shell
System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (24) x64 AMD Ryzen 9 5900X 12-Core Processor
    Memory: 46.74 GB / 62.74 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 18.11.0 - ~/.nvm/versions/node/v18.11.0/bin/node
    npm: 8.19.2 - ~/.nvm/versions/node/v18.11.0/bin/npm
  Browsers:
    Firefox: 106.0
```

### Used Package Manager

pnpm@7.13.5

### Additional context

`.npmrc`
```
audit=false
engine-strict=true
loglevel=error
fund=false
node-linker=hoisted
prefer-offline=true
progress=false
shamefully-hoist=true
store-dir=.pnpm-store
strict-peer-dependencies=true
update-notifier=false
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/intlify/routing/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/intlify/routing/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kazupon** [comment]
Thank you for your reporting!
This issue has been fixed at v0.8.1!
Please check it!
Thanks!

**Comment by Ingramz** [comment]
Despite the effort put into this already I think this hasn't been quite solved yet.

Reproduction:
```
npx nuxi init nuxt-app
cd nuxt-app
npm install
npm install @nuxtjs/i18n@next
npm ls @vue/composition-api
```

results in:
```
`-- @nuxtjs/i18n@8.0.0-beta.3
  `-- vue-i18n-routing@0.8.1
    +-- @intlify/vue-i18n-bridge@0.7.0
    | `-- @vue/composition-api@1.7.1
    +-- @intlify/vue-router-bridge@0.7.0
    | +-- @vue/composition-api@1.7.1
    | `-- vue-demi@0.13.11
    |   `-- @vue/composition-api@1.7.1 deduped
    +-- @vue/composition-api@1.7.1
    `-- vue-demi@0.13.11
      `-- @vue/composition-api@1.7.1 deduped
```

I think the problem comes from referring `@vue/composition-api` in `optionalDependencies`. Without specifying `--omit=optional` flag, the behavior is to try install these dependencies anyway, which is undesired. It would be better if `@vue/composition-api` was referenced just as an optional peer dependency instead:

```
  "peerDependencies": {
    "@vue/composition-api": "^1.0.0-rc.1"
  },
  "peerDependenciesMeta": {
    "@vue/composition-api": {
      "optional": true
    }
  }
```

There should be no other mentions of `@vue/composition-api` in `package.json`. If that package is needed, it should be vue-demi's (or similar) responsibility of installing it.

**Comment by kazupon** [comment]
Hi!

> Despite the effort put into this already I think this hasn't been quite solved yet.

Could you tell us your npm version please?
I tried to install with npm v9.0.0, so I didn't meet the peer dependencies error.

I've already fixed it at vue-i18n-routing v0.8.1
https://github.com/intlify/routing/pull/22/files

**Comment by Ingramz** [comment]
I'm using npm 8.19.2.

The change you made is not enough:
1) Anything you define in `peerDependenciesMeta` needs to have a corresponding entry in `peerDependencies` for it to take effect.
2) You are still including `@vue/composition-api` in `optionalDependencies`, this is what forces pnpm and npm to install `@vue/composition-api` every time.

**Comment by kazupon** [comment]
close
