### ISSUE TITLE
expose `defaultLocale`

### ISSUE THREAD

**Issue by jd1378** [intlify/routing#39]
### Clear and concise description of the problem

I'm using a modified version of `nuxt-seo-kit` and I'm using it's breadcrumbs
I have modified it to include or omit language codes in the breadcrumb it creates 

the problem is, on main page, I have to have a way to detect and omit the default locale's language code for the main page, since default language does not include language code in it's url

currently there's no way to get the defaultLocale set in the config that I'm aware of, cleanly (without using some env variable)

### Suggested solution

expose it using a composable ? I'm not sure what's the best way to expose it.

### Alternative

the alternative is to simply use runtime config

it won't be clean and it can't be included in a PR for nuxt-seo-kit

### Validations

- [X] Follow our [Code of Conduct](https://github.com/intlify/routing/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/intlify/routing/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by jd1378** [comment]
sorry I think I made issue in the wrong repo

**Comment by jd1378** [comment]
no It's right, It's just that it's a dependency for https://github.com/nuxt-modules/i18n, but it has to be implemented here first

**Comment by kazupon** [comment]
Thank you for your reporting!
And, sorry my late response.

`defaultLocale` has been exported by https://github.com/nuxt-modules/i18n/pull/2144
